import type { ActiveCase } from "@/types";

// Individual reported cases shown as clickable dots on the map.
// MOCK data for now. Later this is replaced by a Supabase query against the
// `active_cases` table (see lib/data.ts#getActiveCases for the seam + the
// status/expires_at filter the backend should apply).
export const activeCases: ActiveCase[] = [
  {
    id: "ac1",
    caseType: "dengue",
    title: "Dengue Report",
    locationName: "Tanjong Pagar Block 12",
    lat: 1.2769,
    lng: 103.8451,
    distanceKm: 1.2,
    reportedAgo: "8 min ago",
    status: "active",
    riskLevel: "high",
    description:
      "A citizen reported multiple mosquito breeding spots near the residential block. NEA inspection may be required.",
    imageUrls: ["/images/reports/dengue-water-1.svg", "/images/reports/dengue-site-2.svg"],
    reportedBy: "Citizen Report",
    nearbyCases: 14,
  },
  {
    id: "ac2",
    caseType: "covid",
    title: "COVID-19 Report",
    locationName: "Raffles Place MRT Exit B",
    lat: 1.2839,
    lng: 103.8515,
    distanceKm: 2.4,
    reportedAgo: "18 min ago",
    status: "active",
    riskLevel: "medium",
    description:
      "Increased crowd density was reported during peak hour. Monitoring is recommended.",
    imageUrls: ["/images/reports/crowd-mrt-1.svg"],
    reportedBy: "Anonymous Citizen",
    nearbyCases: 6,
  },
  {
    id: "ac3",
    caseType: "flu",
    title: "Influenza Report",
    locationName: "Queenstown Clinic Area",
    lat: 1.2942,
    lng: 103.7861,
    distanceKm: 4.1,
    reportedAgo: "1 hr ago",
    status: "active",
    riskLevel: "low",
    description: "Several flu-related visits were reported around the clinic area.",
    imageUrls: [],
    reportedBy: "Citizen Report",
    nearbyCases: 3,
  },
  // A few extra reports so the map has more clickable cases to demo.
  {
    id: "ac4",
    caseType: "dengue",
    title: "Dengue Report",
    locationName: "Geylang Lorong 21",
    lat: 1.3171,
    lng: 103.8862,
    distanceKm: 3.6,
    reportedAgo: "32 min ago",
    status: "active",
    riskLevel: "high",
    description:
      "Stagnant water collecting in discarded containers behind the coffee shop. Several residents reported bites.",
    imageUrls: ["/images/reports/dengue-water-1.svg"],
    reportedBy: "Citizen Report",
    nearbyCases: 9,
  },
  {
    id: "ac5",
    caseType: "covid",
    title: "COVID-19 Report",
    locationName: "Bedok Bus Interchange",
    lat: 1.3239,
    lng: 103.9301,
    distanceKm: 6.8,
    reportedAgo: "44 min ago",
    status: "active",
    riskLevel: "medium",
    description: "Reporter noted several commuters with flu-like symptoms in a crowded queue.",
    imageUrls: ["/images/reports/crowd-mrt-1.svg"],
    reportedBy: "Anonymous Citizen",
    nearbyCases: 5,
  },
  {
    id: "ac6",
    caseType: "flu",
    title: "Influenza Report",
    locationName: "Hougang Ave 8",
    lat: 1.3718,
    lng: 103.8901,
    distanceKm: 9.2,
    reportedAgo: "2 hr ago",
    status: "active",
    riskLevel: "low",
    description: "Cluster of flu cases reported at a childcare centre.",
    imageUrls: [],
    reportedBy: "Citizen Report",
    nearbyCases: 4,
  },
];
