import type { Hospital } from "@/types";

// Department splits sum to each hospital's total / occupied beds.
export const hospitals: Hospital[] = [
  {
    id: "stmary",
    name: "St. Mary's Hospital",
    lat: 1.279,
    lng: 103.84,
    occupancy: 54,
    totalBeds: 235,
    occupied: 133,
    available: 102,
    type: "Public Hospital",
    address: "12 Outram Rd, Singapore",
    phone: "+65 6321 4000",
    departments: [
      { name: "Emergency Department", total: 40, occupied: 28 },
      { name: "ICU", total: 25, occupied: 18 },
      { name: "General Ward", total: 110, occupied: 60 },
      { name: "Maternity Ward", total: 30, occupied: 14 },
      { name: "Pediatric Ward", total: 30, occupied: 13 },
    ],
  },
  {
    id: "tpmc",
    name: "Tanjong Pagar Medical Centre",
    lat: 1.2767,
    lng: 103.8456,
    occupancy: 87,
    totalBeds: 180,
    occupied: 157,
    available: 23,
    type: "Medical Centre",
    address: "1 Tanjong Pagar Plaza, Singapore",
    phone: "+65 6225 7890",
    departments: [
      { name: "Emergency Department", total: 35, occupied: 32 },
      { name: "ICU", total: 20, occupied: 19 },
      { name: "General Ward", total: 80, occupied: 72 },
      { name: "Maternity Ward", total: 25, occupied: 20 },
      { name: "Pediatric Ward", total: 20, occupied: 14 },
    ],
  },
  {
    id: "queenstown",
    name: "Queenstown General Hospital",
    lat: 1.2942,
    lng: 103.7861,
    occupancy: 34,
    totalBeds: 210,
    occupied: 71,
    available: 139,
    type: "Public Hospital",
    address: "90 Stirling Rd, Singapore",
    phone: "+65 6471 2233",
    departments: [
      { name: "Emergency Department", total: 40, occupied: 18 },
      { name: "ICU", total: 24, occupied: 9 },
      { name: "General Ward", total: 96, occupied: 30 },
      { name: "Maternity Ward", total: 26, occupied: 8 },
      { name: "Pediatric Ward", total: 24, occupied: 6 },
    ],
  },
  {
    id: "bukittimah",
    name: "Bukit Timah Community Hospital",
    lat: 1.3294,
    lng: 103.8021,
    occupancy: 28,
    totalBeds: 160,
    occupied: 45,
    available: 115,
    type: "Community Hospital",
    address: "10 Jln Anak Bukit, Singapore",
    phone: "+65 6466 5500",
    departments: [
      { name: "Emergency Department", total: 30, occupied: 12 },
      { name: "ICU", total: 18, occupied: 5 },
      { name: "General Ward", total: 72, occupied: 18 },
      { name: "Maternity Ward", total: 20, occupied: 6 },
      { name: "Pediatric Ward", total: 20, occupied: 4 },
    ],
  },
  {
    id: "sengkang",
    name: "Sengkang Emergency Hospital",
    lat: 1.3868,
    lng: 103.8914,
    occupancy: 91,
    totalBeds: 190,
    occupied: 173,
    available: 17,
    type: "Emergency Hospital",
    address: "110 Sengkang E Way, Singapore",
    phone: "+65 6930 1000",
    departments: [
      { name: "Emergency Department", total: 36, occupied: 34 },
      { name: "ICU", total: 22, occupied: 21 },
      { name: "General Ward", total: 84, occupied: 78 },
      { name: "Maternity Ward", total: 24, occupied: 22 },
      { name: "Pediatric Ward", total: 24, occupied: 18 },
    ],
  },
];
